# Generated by Django 4.2.1 on 2023-06-05 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location_name', models.CharField(max_length=200)),
                ('start_location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_location_name', models.CharField(max_length=200)),
                ('end_location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
